---
# tasks file for deploy-db

- name: install postgres
  yum:
    name: postgresql-server
    state: latest

- name: enable postgres at boot
  service:
    name: postgresql
    enabled: yes

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ pgs_data_dir }}/PG_VERSION"
  register: pgdata_dir_version

- name: Debug pgdata_dir_version
  debug:
    msg: "{{ pgdata_dir_version }}"
    verbosity: 2

- name: Ensure PostgreSQL database is initialized.
  command: "initdb -D {{ pgs_data_dir }}"
  when: not pgdata_dir_version.stat.exists
  become: yes
  become_user: "{{ postgresql_user }}"

- name: start postgres
  service:
    name: postgresql.service
    state: started
